### PR TITLE
vendor dependencies using go mod

### PR DESCRIPTION
**Pull request by rmb938**
Changes:

* Vender stuff using go mod

### CODE REVIEW

**Comment by rmb938** [comment]
I think everything still works 🤷‍♂️ I haven't really touched grpc so not really sure what to look out for.

**Comment by farcaller** [comment]
I'd prefer go mod to dep. Any reason in particular for not using go mod?

Can you extract the protobuf changes and the context changes into dedicated PRs please? The vendoring change is massive and it's easy for minor changes to be lost in the noise.

**Comment by rmb938** [comment]
I used dep just because that is what I'm used to but I can switch it to go mod.

Yup I'll move the changes into separate prs!

**Comment by rmb938** [comment]
@farcaller I re-vendored using go mod. One Issue I am running into is I am unable to build, when I do I get this error:

```
go build .                                                                                                                                                                                                                                                                                                  08:27:29
# github.com/google/lvmd/vendor/github.com/google/credstore/client
vendor/github.com/google/credstore/client/client.go:28:12: undefined: metadata.FromContext
vendor/github.com/google/credstore/client/client.go:37:8: undefined: metadata.NewContext
vendor/github.com/google/credstore/client/server.go:49:13: undefined: metadata.FromContext
```

I am guessing it's because credstore was built with an old version of grpc.

**Comment by rmb938** [comment]
I have no problem making a pr against credstore to fix it but I am not sure which methods to replace those with.

https://godoc.org/google.golang.org/grpc/metadata

There is now

```
func NewIncomingContext(ctx context.Context, md MD) context.Context
func NewOutgoingContext(ctx context.Context, md MD) context.Context
```

and

```
func FromIncomingContext(ctx context.Context) (md MD, ok bool)
func FromOutgoingContext(ctx context.Context) (MD, bool)
```

No idea which ones are the correct ones to use

**Comment by rmb938** [comment]
@farcaller Ok everything should be good now, it builds with no issues.

**Pull request merged**
